Update to net-snmp 5.6
Latest upstream version released 2010-10-07

diff --git a/local/mib2c-update b/local/mib2c-update
--- a/local/mib2c-update
+++ b/local/mib2c-update
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: mib2c-update 16702 2007-09-16 09:51:41Z magfr $
+# $Id: mib2c-update 18484 2010-04-08 14:57:14Z rstory $
 #
 # script to merge custom code into updated mib2c code
 #
@@ -39,7 +39,7 @@ debug()
 
 error()
 {
-    echo "ERROR: $@" >2
+    echo "ERROR: $@" >&2
 }
 
 die()
@@ -308,8 +308,16 @@ if [ -f $HOME/.mib2c-updaterc ]; then
     . $HOME/.mib2c-updaterc
 fi
 
-if [ -f .mib2c-updaterc ]; then
-    . .mib2c-updaterc
+if [ -f $PWD/.mib2c-updaterc ]; then
+    . $PWD/.mib2c-updaterc
+else
+   echo "creating example .mib2c-udpaterc. edit as needed and re-run "
+   echo "mib2c-update."
+   
+   echo "UPDATE_OID=ipAddressTable" >> .mib2c-updaterc
+   echo "UPDATE_CONF=mib2c.mfd.conf" >> .mib2c-updaterc
+   echo "UPDATE_MIB2C_OPTS=" >> .mib2c-updaterc
+   echo "#UPDATE_NOPROBE=1" >> .mib2c-updaterc
 fi
 
 check_setup
